const vocabularyList = [
  {
    term: "apple",
    category: "food",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "banana",
    category: "food",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "carrot",
    category: "food",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "doughnut",
    category: "food",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "eggplant",
    category: "food",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "fig",
    category: "food",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "garlic",
    category: "food",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "honey",
    category: "food",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "ice cream",
    category: "food",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "jam",
    category: "food",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "mother",
    category: "family",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "father",
    category: "family",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "sister",
    category: "family",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "brother",
    category: "family",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "grandmother",
    category: "family",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "grandfather",
    category: "family",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "uncle",
    category: "family",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "aunt",
    category: "family",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "cousin",
    category: "family",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "nephew",
    category: "family",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "hello",
    category: "greetings",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "goodbye",
    category: "greetings",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "good morning",
    category: "greetings",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "good night",
    category: "greetings",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "nice to meet you",
    category: "greetings",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "yesterday",
    category: "time",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "today",
    category: "time",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "tomorrow",
    category: "time",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "minute",
    category: "time",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "hour",
    category: "time",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "left",
    category: "directions",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "right",
    category: "directions",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "up",
    category: "directions",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "down",
    category: "directions",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "forward",
    category: "directions",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "backward",
    category: "directions",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "big",
    category: "adjectives",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "small",
    category: "adjectives",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "hot",
    category: "adjectives",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "cold",
    category: "adjectives",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "fast",
    category: "adjectives",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "slow",
    category: "adjectives",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "what is your name?",
    category: "question phrases",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "how are you?",
    category: "question phrases",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "where are you from?",
    category: "question phrases",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "what time is it?",
    category: "question phrases",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "can you help me?",
    category: "question phrases",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "what is this?",
    category: "question phrases",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "why is it important?",
    category: "question phrases",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
  {
    term: "how much does it cost?",
    category: "question phrases",
    mastered: 0,
    needsPractice: 0,
    dontKnow: 0,
  },
];

export default vocabularyList;
